- name: Install K8s on Ubuntu 22.04 (ec2)
  hosts: vm01
  tasks:
    - name: update apt
      shell: sudo apt-get update -y

    - name: install kubectl
      shell: sudo snap install kubectl --classic

    - name: enable microk8s
      shell: sudo snap install microk8s --classic
    
    - name: wait ready
      shell: microk8s status --wait-ready
    
    - name: add group
      shell: sudo usermod -a -G microk8s ubuntu
    
    - name: config to kubectl
      shell: microk8s config > ~/.kube/config
