- name: Install Jenkins on Ubuntu 22.04
  hosts: vm01
  tasks:
    - name: update apt
      shell: sudo apt-get update
    
    - name: install jdk
      shell: sudo apt install openjdk-11-jdk -y

    - name: install apk
      shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

    - name: install apk dep
      shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]  https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
    
    - name: update apt
      shell:  sudo apt update
    
    - name: install jenkins
      shell:  sudo apt install jenkins -y
    
    - name: Add remote "ubuntu" user to "docker" group
      shell: sudo usermod -aG root jenkins
    
    - name: Add remote "ubuntu" user to "docker" group
      shell: sudo usermod -aG docker jenkins