- name: Update software version on vm (ubuntu 24.04)
  hosts: virtualmachines
  become: true
  tasks:
    - name: update apt
      shell: apt update
  
    - name: upgrade version
      shell: apt upgrade -y
# ansible-playbook update-version.yaml -K
